name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022"
        cmake --build . --config Release